---
- name: Prepare
  hosts: all
  tasks:
    - name: Populate /etc/hosts with molecule instances
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}$"
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
      loop: "{{ groups['all'] }}"
      when: groups['all'] | length > 1

    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
          - git
          - openssl
        update_cache: true
      when: ansible_facts.os_family == "Debian"
      retries: 3
      delay: 10
      register: _apt_install
      until: _apt_install is success
