---
- name: Verify Beats TLS security
  hosts: all
  vars:
    elasticstack_elasticsearch_http_port: 9200
    elasticstack_elasticsearch_group_name: elasticsearch
  tasks:
    - name: Set elasticsearch_ca variable
      ansible.builtin.set_fact:
        elasticsearch_ca: "{{ groups[elasticstack_elasticsearch_group_name][0] }}"
      when: elasticsearch_ca is undefined

    - name: Fetch Elastic password
      ansible.builtin.shell: |
        set -o pipefail
        grep "PASSWORD elastic " /usr/share/elasticsearch/initial_passwords |
        awk {' print $4 '}
      args:
        executable: /bin/bash
      register: elastic_pass
      changed_when: false
      delegate_to: "{{ elasticsearch_ca }}"

    - name: Elasticsearch health check
      ansible.builtin.uri:
        url: "https://localhost:{{ elasticstack_elasticsearch_http_port }}/_cluster/health?wait_for_status=yellow&timeout=30s"
        method: GET
        force_basic_auth: true
        user: elastic
        password: "{{ elastic_pass.stdout }}"
        return_content: true
        status_code: 200
        validate_certs: false
      register: result
      until: result.json.status | default('red') in ['green', 'yellow']
      retries: 6
      delay: 10
      when: "'elasticsearch' in group_names"

    - name: Run Beats TLS checks
      when: "'beats' in group_names"
      block:
        - name: Check filebeat service is running
          ansible.builtin.service:
            name: filebeat
            state: started
          check_mode: true
          register: filebeat_svc
          failed_when: filebeat_svc.changed

        - name: Check certificate directory exists
          ansible.builtin.stat:
            path: /etc/beats/certs
          register: certs_dir

        - name: Assert certificate directory exists
          ansible.builtin.assert:
            that:
              - certs_dir.stat.exists
              - certs_dir.stat.isdir
            fail_msg: "Beats certificate directory /etc/beats/certs not found"

        - name: Check beats certificate exists
          ansible.builtin.stat:
            path: "/etc/beats/certs/{{ inventory_hostname }}-beats.crt"
          register: beats_cert

        - name: Assert beats certificate exists
          ansible.builtin.assert:
            that:
              - beats_cert.stat.exists
            fail_msg: "Beats certificate not found"

        - name: Check beats key exists
          ansible.builtin.stat:
            path: "/etc/beats/certs/{{ inventory_hostname }}-beats.key"
          register: beats_key

        - name: Assert beats key exists
          ansible.builtin.assert:
            that:
              - beats_key.stat.exists
            fail_msg: "Beats key not found"

        - name: Check CA certificate exists
          ansible.builtin.stat:
            path: /etc/beats/certs/ca.crt
          register: ca_cert

        - name: Assert CA certificate exists
          ansible.builtin.assert:
            that:
              - ca_cert.stat.exists
            fail_msg: "CA certificate not found on beats node"

        - name: Read filebeat.yml
          ansible.builtin.slurp:
            src: /etc/filebeat/filebeat.yml
          register: filebeat_yml

        - name: Verify SSL configuration in filebeat
          ansible.builtin.assert:
            that:
              - "'ssl' in (filebeat_yml.content | b64decode)"
              - "'certificate_authorities' in (filebeat_yml.content | b64decode)"
              - "'output.elasticsearch' in (filebeat_yml.content | b64decode)"
            fail_msg: "SSL configuration not found in filebeat.yml"
