---
- name: Include global role
  ansible.builtin.import_role:
    name: oddly.elasticstack.elasticstack
  when: not hostvars[inventory_hostname]._elasticstack_role_imported | default(false)

- name: Configure Elastic repositories for selected release
  ansible.builtin.include_tasks: "{{ role_path }}/../elasticstack/tasks/configure_repositories.yml"
