---

- name: Include global role
  ansible.builtin.import_role:
    name: oddly.elasticstack.elasticstack
  when: not hostvars[inventory_hostname]._elasticstack_role_imported | default(false)

- name: Import RedHat tasks
  ansible.builtin.import_tasks: redhat.yml
  when:
    - ansible_facts.os_family == 'RedHat'
    - elasticstack_enable_repos | bool
    - not _elasticstack_repositories_configured | default(false) | bool

- name: Import Debian tasks
  ansible.builtin.import_tasks: debian.yml
  when:
    - ansible_facts.os_family == 'Debian'
    - elasticstack_enable_repos | bool
    - not _elasticstack_repositories_configured | default(false) | bool

- name: Mark Elastic repositories as configured  # noqa: var-naming[no-role-prefix]
  ansible.builtin.set_fact:
    _elasticstack_repositories_configured: true
  when:
    - elasticstack_enable_repos | bool
    - not _elasticstack_repositories_configured | default(false) | bool
