---

# See https://github.com/elastic/elasticsearch/issues/85876
# for more information why this is needed

- name: redhat | Ensure gpg exists, for signing keys
  ansible.builtin.package:
    name: gnupg
    state: present
  register: _repos_gpg_install_rh
  until: _repos_gpg_install_rh is success
  retries: 3
  delay: 10

- name: redhat | Workaround for EL > 8
  when:
    - ansible_facts.distribution_major_version | int >= 9
  block:

    - name: redhat | Show a warning
      ansible.builtin.debug:
        msg: "For this workaround to work, please set elasticstack_rpm_workaround to true"
      when:
        - not elasticstack_rpm_workaround | bool

    - name: redhat | Enable workaround for rpm keys
      when:
        - elasticstack_rpm_workaround | bool
      block:

        - name: redhat | Install crypto-policies-scripts
          ansible.builtin.package:
            name: crypto-policies-scripts
          register: _repos_crypto_policies_install
          until: _repos_crypto_policies_install is success
          retries: 3
          delay: 10

        - name: redhat | Check current crypto policy
          ansible.builtin.command: update-crypto-policies --show
          register: _repos_crypto_policy
          changed_when: false

        - name: redhat | Set Crypto policies to legacy
          ansible.builtin.command: "update-crypto-policies --set LEGACY"
          changed_when: true
          when: _repos_crypto_policy.stdout != 'LEGACY'

- name: redhat | Ensure Elastic repository key is available (RedHat)
  ansible.builtin.rpm_key:
    key: "{{ elasticstack_repo_key }}"
    state: present

- name: redhat | Ensure Elastic Stack yum repository is configured (RedHat)
  ansible.builtin.yum_repository:
    name: elastic-{{ elasticstack_release }}.x
    description: Elastic Release {{ elasticstack_release }}.x
    file: elastic-release
    baseurl: "{{ elasticstack_repo_base_url }}/packages/{{ elasticstack_release }}.x/yum"
    gpgcheck: true
    gpgkey: "{{ elasticstack_repo_key }}"
    enabled: "{{ elasticstack_enable_repos | bool }}"
