---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Populate /etc/hosts with molecule instances
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}$"
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
      loop: "{{ groups['all'] }}"
      when: groups['all'] | length > 1
