---
# Bootstrap Python 3.12 on RHEL 8 before any Python-dependent tasks
- name: Bootstrap Python 3.12 on RHEL 8
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if this is RHEL 8 (using raw module to avoid Python dependency)
      ansible.builtin.raw: |
        if [ -f /etc/redhat-release ] && grep -q "release 8" /etc/redhat-release; then
          echo "rhel8"
        else
          echo "other"
        fi
      register: os_check
      changed_when: false

    - name: Install Python 3.12 on RHEL 8
      ansible.builtin.raw: dnf install -y python3.12 python3.12-pip
      when: "'rhel8' in os_check.stdout"
      changed_when: true

    - name: Set Python 3.12 as default python3 on RHEL 8
      ansible.builtin.raw: |
        alternatives --set python3 /usr/bin/python3.12 2>/dev/null || \
        ln -sf /usr/bin/python3.12 /usr/bin/python3
      when: "'rhel8' in os_check.stdout"
      changed_when: true

- name: Prepare
  hosts: all
  tasks:
    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - git
        update_cache: yes
      when: ansible_os_family == "Debian"

    #- name: Create Logstash directory
    #  ansible.builtin.file:
    #    path: /etc/logstash
    #    owner: root
    #    group: root
    #    mode: 0755
    #    state: directory

    #- name: Create Logstash conf.d
    #  ansible.builtin.file:
    #    path: /etc/logstash/conf.d
    #    owner: root
    #    group: root
    #    mode: 0755
    #    state: directory

    #- name: Create Logstash syslog pipeline
    #  ansible.builtin.file:
    #    path: /etc/logstash/conf.d/syslog
    #    owner: root
    #    group: root
    #    mode: 0755
    #    state: directory

    #- name: Create Syslog input
    #  ansible.builtin.copy:
    #    dest: /etc/logstash/conf.d/syslog/input.conf
    #    content: >
    #      "input {
    #         redis {
    #           key => input
    #           host => localhost
    #           data_type => list
    #         }
    #       }
    #      "

    #- name: Create Syslog output
    #  ansible.builtin.copy:
    #    dest: /etc/logstash/conf.d/syslog/output.conf
    #    content: >
    #      "output {
    #         redis {
    #           key => input
    #           host => localhost
    #           data_type => list
    #         }
    #       }
    #      "
