namespace: oddly
name: elasticstack
version: 1.0.0
readme: README.md
authors:
  - Sam Crauwels <sam.crauwels@gmail.com>
  - Alexander Stoll <alexander.stoll@netways.de>
  - Markus Frosch <markus.frosch@netways.de>
  - Patrick Dolinic <patrick.dolinic@netways.de>
  - Thilo Wening <thilo.wening@netways.de>
  - Thomas Widhalm <thomas.widhalm@netways.de>
description: >-
  Ansible collection for the Elastic Stack with ES 9.x support.
  Installs and configures Elasticsearch, Kibana, Logstash, and Beats.
  Forked from netways.elasticstack.
requires_ansible: ">=2.18.0"
license:
  - GPL-3.0
license_file: 'LICENSE'
tags:
  - elastic
  - elasticsearch
  - kibana
  - logstash
  - beat
  - metricbeat
  - filebeat
  - monitoring
dependencies:
  "community.general": "*"
repository: https://github.com/Oddly/ansible-collection-elasticstack
documentation: https://github.com/Oddly/ansible-collection-elasticstack/blob/main/README.md
homepage: https://github.com/Oddly/ansible-collection-elasticstack
issues: https://github.com/Oddly/ansible-collection-elasticstack/issues
build_ignore:
  - .github
  - .cache
  - molecule
  - .gitignore
  - daemon.json
  - .mailmap
  - '*.tar.gz'
  - 'venv*'
