---
# Elasticsearch 8.x to 9.x upgrade test
#
# This scenario tests a rolling upgrade from Elasticsearch 8.x to 9.x:
# 1. Install ES 8.x cluster (2 nodes)
# 2. Verify cluster is green
# 3. Index some test data
# 4. Upgrade to ES 9.x (rolling upgrade)
# 5. Verify cluster is green and data preserved

- name: Install Elasticsearch 8.x (initial deployment)
  collections:
    - oddly.elasticstack
  hosts: all
  vars:
    elasticstack_full_stack: false
    elasticstack_release: 8
    elasticsearch_jna_workaround: true
    elasticsearch_disable_systemcallfilterchecks: true
    elasticsearch_heap: "1"
    elasticstack_no_log: false
  tasks:
    - name: Include Elastic repos role (8.x)
      ansible.builtin.include_role:
        name: repos

    - name: Include Elasticsearch role (8.x)
      ansible.builtin.include_role:
        name: elasticsearch

- name: Verify ES 8.x cluster is healthy and index test data
  hosts: elasticsearch[0]
  vars:
    elasticstack_elasticsearch_http_port: 9200
    elasticstack_initial_passwords: /usr/share/elasticsearch/initial_passwords
  tasks:
    - name: Fetch Elastic password
      ansible.builtin.shell: |
        grep "PASSWORD elastic " {{ elasticstack_initial_passwords }} |
        awk {' print $4 '}
      register: elastic_pass
      changed_when: false

    - name: Wait for ES cluster to be healthy
      ansible.builtin.uri:
        url: https://localhost:{{ elasticstack_elasticsearch_http_port }}/_cluster/health
        method: GET
        force_basic_auth: yes
        user: elastic
        password: "{{ elastic_pass.stdout }}"
        return_content: yes
        status_code: 200
        validate_certs: false
      register: cluster_health
      retries: 12
      delay: 10
      until: cluster_health.json.status | default('') in ['green', 'yellow']

    - name: Display ES 8.x cluster health
      ansible.builtin.debug:
        var: cluster_health.json

    - name: Check ES version is 8.x
      ansible.builtin.uri:
        url: https://localhost:{{ elasticstack_elasticsearch_http_port }}/
        method: GET
        force_basic_auth: yes
        user: elastic
        password: "{{ elastic_pass.stdout }}"
        return_content: yes
        validate_certs: false
      register: es_info

    - name: Verify ES 8.x is running
      ansible.builtin.assert:
        that:
          - es_info.json.version.number is version('8.0.0', '>=')
          - es_info.json.version.number is version('9.0.0', '<')
        fail_msg: "Expected ES 8.x but got {{ es_info.json.version.number }}"
        success_msg: "ES 8.x ({{ es_info.json.version.number }}) is running"

    - name: Create test index with some data
      ansible.builtin.uri:
        url: https://localhost:{{ elasticstack_elasticsearch_http_port }}/upgrade-test-index/_doc/1
        method: PUT
        force_basic_auth: yes
        user: elastic
        password: "{{ elastic_pass.stdout }}"
        body_format: json
        body:
          test_field: "pre-upgrade-data"
          timestamp: "{{ ansible_date_time.iso8601 }}"
        validate_certs: false
        status_code: [200, 201]
      register: index_result

    - name: Display indexing result
      ansible.builtin.debug:
        var: index_result

    - name: Refresh index
      ansible.builtin.uri:
        url: https://localhost:{{ elasticstack_elasticsearch_http_port }}/upgrade-test-index/_refresh
        method: POST
        force_basic_auth: yes
        user: elastic
        password: "{{ elastic_pass.stdout }}"
        validate_certs: false

- name: Upgrade to Elasticsearch 9.x (with config change to exercise handler suppression)
  collections:
    - oddly.elasticstack
  hosts: all
  vars:
    elasticstack_full_stack: false
    elasticstack_release: 9
    elasticsearch_jna_workaround: true
    elasticsearch_disable_systemcallfilterchecks: true
    elasticsearch_heap: "1"
    elasticstack_no_log: false
    # Add a JVM custom parameter during upgrade to trigger a config change.
    # This exercises the fix: the rolling upgrade restarts ES, and the config
    # change notifies the handler, which should be suppressed to prevent an
    # uncontrolled second restart.
    elasticsearch_jvm_custom_parameters:
      - "-Des.upgrade.test.marker=true"
  tasks:
    - name: Include Elastic repos role (9.x)
      ansible.builtin.include_role:
        name: repos

    # In a real upgrade, users run the role in a separate playbook execution
    # where _elasticstack_role_imported is not set. Since this test combines
    # initial install and upgrade in one playbook, we reset the guard so the
    # shared role re-runs (to fetch the elastic password needed by the rolling
    # upgrade).
    - name: Reset shared role guard for upgrade play
      ansible.builtin.set_fact:
        _elasticstack_role_imported: false

    - name: Gather package facts for version comparison
      ansible.builtin.package_facts:
        manager: auto

    - name: Detect latest available Elasticsearch 9.x version
      ansible.builtin.shell: >
        apt-cache policy elasticsearch | grep 'Candidate:' | awk '{print $2}'
      register: _es_candidate_version
      changed_when: false

    - name: Set target upgrade version
      ansible.builtin.set_fact:
        elasticstack_version: "{{ _es_candidate_version.stdout }}"

    - name: Display upgrade target
      ansible.builtin.debug:
        msg: "Upgrading from {{ ansible_facts.packages['elasticsearch'][0].version }} to {{ elasticstack_version }}"

    - name: Include Elasticsearch role (upgrade to 9.x)
      ansible.builtin.include_role:
        name: elasticsearch
