---
- name: Prepare
  hosts: all
  vars:
    distro_cache_url: "{{ lookup('env', 'DISTRO_CACHE_URL') }}"
  tasks:
    - name: Common prepare tasks
      ansible.builtin.include_tasks: ../shared/prepare_common.yml

    - name: Create custom data directory
      ansible.builtin.file:
        path: /data/elasticsearch
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create custom log directory
      ansible.builtin.file:
        path: /var/log/elasticsearch-custom
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create snapshot repository directory
      ansible.builtin.file:
        path: /mnt/es-snapshots
        state: directory
        owner: root
        group: root
        mode: "0755"
