---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "cert-renew-es1-${MOLECULE_DISTRO:-debian12}-r${ELASTIC_RELEASE:-9}"
    groups:
      - elasticsearch
      - logstash
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: "cert-renew-net-${MOLECULE_DISTRO:-debian12}-r${ELASTIC_RELEASE:-9}"
  - name: "cert-renew-es2-${MOLECULE_DISTRO:-debian12}-r${ELASTIC_RELEASE:-9}"
    groups:
      - elasticsearch
      - kibana
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: "cert-renew-net-${MOLECULE_DISTRO:-debian12}-r${ELASTIC_RELEASE:-9}"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
