---
- name: Converge
  hosts: all
  collections:
    - oddly.elasticstack
  vars:
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | default(9, true) | int }}"
    elasticstack_full_stack: false
    elasticstack_no_log: false
    logstash_pipeline_unsafe_shutdown: true
    logstash_custom_pipeline: |
      input {
        generator {
          message => "custom pipeline test"
          count => 1
        }
      }
      filter {
        mutate {
          add_field => { "custom_field" => "custom_value" }
        }
      }
      output {
        stdout {
          codec => rubydebug
        }
      }
  tasks:
    - name: Include Elastic repos role
      ansible.builtin.include_role:
        name: repos

    - name: Include Logstash role with custom pipeline
      ansible.builtin.include_role:
        name: logstash
