---
- name: Converge
  hosts: all
  collections:
    - oddly.elasticstack
  vars:
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | default(9, true) | int }}"
    elasticstack_full_stack: false
    elasticstack_no_log: false
    logstash_pipeline_unsafe_shutdown: true
    logstash_output_elasticsearch: false
    logstash_cert_source: external
    logstash_tls_certificate_file: "/tmp/test-certs/server.crt"
    logstash_tls_key_file: "/tmp/test-certs/server.key"
    logstash_tls_ca_file: "/tmp/test-certs/ca.crt"
    logstash_input_beats_ssl: true
  tasks:
    - name: Install openssl for certificate generation
      ansible.builtin.package:
        name: openssl
        state: present

    - name: Create test certificate directory
      ansible.builtin.file:
        path: /tmp/test-certs
        state: directory
        mode: "0755"

    - name: Generate test CA private key
      community.crypto.openssl_privatekey:
        path: /tmp/test-certs/ca.key
        size: 2048

    - name: Generate test CA certificate
      community.crypto.x509_certificate:
        path: /tmp/test-certs/ca.crt
        privatekey_path: /tmp/test-certs/ca.key
        provider: selfsigned
        selfsigned_not_after: "+365d"

    - name: Generate test server private key
      community.crypto.openssl_privatekey:
        path: /tmp/test-certs/server.key
        size: 2048

    - name: Generate test server CSR
      community.crypto.openssl_csr:
        path: /tmp/test-certs/server.csr
        privatekey_path: /tmp/test-certs/server.key
        common_name: "{{ inventory_hostname }}"
        subject_alt_name:
          - "DNS:{{ inventory_hostname }}"
          - "DNS:localhost"
          - "IP:127.0.0.1"

    - name: Generate test server certificate
      community.crypto.x509_certificate:
        path: /tmp/test-certs/server.crt
        csr_path: /tmp/test-certs/server.csr
        ownca_path: /tmp/test-certs/ca.crt
        ownca_privatekey_path: /tmp/test-certs/ca.key
        provider: ownca
        ownca_not_after: "+365d"

    - name: Include Elastic repos role
      ansible.builtin.include_role:
        name: repos

    - name: Include Logstash role with external certs
      ansible.builtin.include_role:
        name: logstash
