---
- name: Prepare
  hosts: all
  vars:
    distro_cache_url: "{{ lookup('env', 'DISTRO_CACHE_URL') }}"
  tasks:
    - name: Common prepare tasks
      ansible.builtin.include_tasks: ../shared/prepare_common.yml

    - name: Create filter files directory on controller
      ansible.builtin.file:
        path: /tmp/logstash-filters
        state: directory
        mode: "0755"
      delegate_to: localhost
      run_once: true  # noqa: run-once[task]

    - name: Create a custom filter file on controller
      ansible.builtin.copy:
        dest: /tmp/logstash-filters/20-custom-filter.conf
        content: |
          filter {
            mutate {
              add_field => { "custom_filter_applied" => "true" }
            }
          }
        mode: "0644"
      delegate_to: localhost
      run_once: true  # noqa: run-once[task]
