---
- name: Prepare
  hosts: all
  tasks:
    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
        update_cache: true
      when: ansible_facts.os_family == "Debian"

    - name: Create filter files directory
      ansible.builtin.file:
        path: /tmp/logstash-filters
        state: directory
        mode: "0755"

    - name: Create a custom filter file
      ansible.builtin.copy:
        dest: /tmp/logstash-filters/20-custom-filter.conf
        content: |
          filter {
            mutate {
              add_field => { "custom_filter_applied" => "true" }
            }
          }
        mode: "0644"
