---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  vars:
    elasticstack_full_stack: false
    elasticsearch_jna_workaround: true
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | default('9', true) | int }}"
    elasticstack_no_log: false
  tasks:
    - name: Include Elastic repos role
      ansible.builtin.include_role:
        name: oddly.elasticstack.repos
    - name: Include Beats
      ansible.builtin.include_role:
        name: oddly.elasticstack.beats
