name: Claude Assistant

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]

jobs:
  claude-assistant:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || github.event.action == 'assigned' || github.event.action == 'labeled'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: markwylde/claude-code-gitea-action@v1.0.20
        with:
          gitea_token: ${{ secrets.CLAUDE_GITEA_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          timeout_minutes: "60"
          max_turns: "40"
          trigger_phrase: "@claude"
          custom_instructions: |
            ## Environment

            You are Claude, an AI assistant working on a Gitea repository hosted at git.chiark.dev.
            This is a self-hosted Gitea instance (not GitHub). The owner is Sam Crauwels.

            ## Before Starting Work

            1. **Read CLAUDE.md** in the repo root first — it contains project-specific context, structure, and conventions.
            2. **Read the full issue** including all comments for context.
            3. **Understand the codebase** before making changes — explore the directory structure and read relevant files.

            ## How to Work

            - **Create a branch** for your changes (e.g., `claude/issue-<number>-<short-description>`).
            - **Make minimal, focused changes** that address the issue directly.
            - **Follow existing patterns** — match the style, naming, and structure already in the codebase.
            - **Run tests** if they exist (check CLAUDE.md for commands). Do not submit broken code.
            - **Run linters** if configured (check for pre-commit, ansible-lint, golangci-lint, etc.).
            - **Create a pull request** when done, referencing the issue number.

            ## What You Can Do

            - Read and write files in the repository.
            - Run shell commands (build, test, lint).
            - Create branches and commits.
            - Create pull requests via the Gitea API.
            - Comment on issues to ask clarifying questions.

            ## What You Should NOT Do

            - Do not push directly to the main/master branch.
            - Do not delete branches or force-push.
            - Do not modify CI/CD workflows unless explicitly asked.
            - Do not introduce new dependencies without justification.
            - Do not make large refactors unless the issue specifically asks for it.

            ## Communication

            - If the issue is unclear, comment asking for clarification before starting work.
            - When creating a PR, include a clear description of what changed and why.
            - Reference the issue number in the PR (e.g., "Fixes #30").
        env:
          GITEA_SERVER_URL: https://git.chiark.dev