---
name: Test Role beats
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/beats/**'
      - '.gitea/workflows/test_role_beats.yml'
      - 'molecule/beats_**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_beats:
    uses: ./.gitea/workflows/test_linting.yml
    with:
      rolename: beats

  molecule_beats:
    needs: lint_beats
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      matrix:
        distro:
          - rockylinux9
          - rockylinux10
          - ubuntu2204
          - ubuntu2404
          - debian11
          - debian12
          - debian13
        scenario: [beats_default, beats_peculiar, beats_advanced, beats_security]
        release: [8, 9]

    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1


      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 -r requirements-test.txt
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a ../ansible-collection-$COLLECTION_NAME ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with molecule
        run: molecule test -s ${{ matrix.scenario }} --destroy=never
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_DIFF_ALWAYS: 'true'
          ANSIBLE_CALLBACKS_ENABLED: profile_tasks
          ELASTIC_RELEASE: ${{ matrix.release }}

      - name: Collect and upload diagnostics
        if: failure()
        uses: ./.github/actions/collect-diagnostics
        with:
          artifact-name: diag-${{ matrix.scenario }}-${{ matrix.distro }}-r${{ matrix.release }}

      - name: Cleanup molecule
        if: always()
        run: molecule destroy -s ${{ matrix.scenario }}
        continue-on-error: true
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
