---
name: Test Elasticsearch Upgrade 8→9
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 02:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_elasticsearch:
    uses: ./.gitea/workflows/test_linting.yml
    with:
      rolename: elasticsearch

  upgrade_multi_node:
    needs: lint_elasticsearch
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian12
          - rockylinux9
        scenario:
          - elasticsearch_upgrade_8to9

    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install dependencies
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 -r requirements-test.txt
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a "$GITHUB_WORKSPACE" ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with molecule
        run: molecule test -s ${{ matrix.scenario }} --destroy=never
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_DIFF_ALWAYS: 'true'
          ANSIBLE_CALLBACKS_ENABLED: profile_tasks

      - name: Collect and upload diagnostics
        if: failure()
        uses: ./.github/actions/collect-diagnostics
        with:
          artifact-name: diag-${{ matrix.scenario }}-${{ matrix.distro }}

      - name: Cleanup molecule
        if: always()
        run: molecule destroy -s ${{ matrix.scenario }}
        continue-on-error: true
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}

  upgrade_single_node:
    needs: lint_elasticsearch
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian12
        scenario:
          - elasticsearch_upgrade_8to9_single

    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install dependencies
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 -r requirements-test.txt
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a "$GITHUB_WORKSPACE" ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with molecule
        run: molecule test -s ${{ matrix.scenario }} --destroy=never
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_DIFF_ALWAYS: 'true'
          ANSIBLE_CALLBACKS_ENABLED: profile_tasks

      - name: Collect and upload diagnostics
        if: failure()
        uses: ./.github/actions/collect-diagnostics
        with:
          artifact-name: diag-${{ matrix.scenario }}-${{ matrix.distro }}

      - name: Cleanup molecule
        if: always()
        run: molecule destroy -s ${{ matrix.scenario }}
        continue-on-error: true
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
