---
name: Test Plugins
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'plugins/**'
      - '.gitea/workflows/test_plugins.yml'
      - 'molecule/plugins/**'
      - '.config/pycodestyle.cfg'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install test dependencies.
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 pycodestyle
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Lint code.
        run: |
          pycodestyle plugins/ --config=.config/pycodestyle.cfg --statistics --count

  sanity:
    needs: pycodestyle
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        ansible_core: ["2.18", "2.19", "2.20"]

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install ansible-core
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 ansible-core~=${{ matrix.ansible_core }}.0
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a $GITHUB_WORKSPACE ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Run ansible-test sanity
        run: |
          cd ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
          ansible-test sanity --python 3.12 --color yes \
            --skip-test validate-modules \
            plugins/
        env:
          PY_COLORS: '1'

  unit-test:
    needs: [pycodestyle, sanity]
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 ansible 'elasticsearch>=8,<10'
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a $GITHUB_WORKSPACE ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test `cert_info` module
        run: python3 tests/unit/plugins/modules/test_cert_info.py
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Test `certs` module util
        run: python3 tests/unit/plugins/module_utils/test_certs.py
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Test `api` module util
        run: python3 tests/unit/plugins/module_utils/test_api.py
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  python:
    needs: unit-test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 ansible
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a $GITHUB_WORKSPACE ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with ansible-playbook
        run: |
          ansible-playbook molecule/plugins/converge.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  ansible-core:
    needs: python
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      matrix:
        ansible_core_version: [2.18.12, 2.19.5, 2.20.1]

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 ansible-core==${{ matrix.ansible_core_version }}
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a $GITHUB_WORKSPACE ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with ansible-playbook
        run: |
          ansible-playbook molecule/plugins/converge.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  python-cryptography:
    needs: ansible-core
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      matrix:
        python_cryptography_version: [41.0.7, 42.0.8, 43.0.3, 44.0.3, 45.0.7, 46.0.4]

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system --break-system-packages --python /usr/bin/python3 cryptography==${{ matrix.python_cryptography_version }}
          uv pip install --system --break-system-packages --python /usr/bin/python3 ansible
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a $GITHUB_WORKSPACE ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with ansible-playbook
        run: |
          ansible-playbook molecule/plugins/converge.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
