---
name: Test Role Kibana
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/kibana/**'
      - '.gitea/workflows/test_role_kibana.yml'
      - 'molecule/kibana_**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_kibana:
    uses: ./.gitea/workflows/test_linting.yml
    with:
      rolename: kibana

  molecule_kibana:
    needs: lint_kibana
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      matrix:
        distro:
          - rockylinux9
          - rockylinux10
          - ubuntu2204
          - ubuntu2404
          - debian11
          - debian12
          - debian13
        scenario: [kibana_default]
        release: [8, 9]

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install dependencies
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 -r requirements-test.txt
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a $GITHUB_WORKSPACE ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with molecule
        run: molecule test -s ${{ matrix.scenario }} --destroy=never
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          ELASTIC_RELEASE: ${{ matrix.release }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_DIFF_ALWAYS: 'true'
          ANSIBLE_CALLBACKS_ENABLED: profile_tasks

      - name: Collect and upload diagnostics
        if: failure()
        uses: ./.github/actions/collect-diagnostics
        with:
          artifact-name: diag-${{ matrix.scenario }}-${{ matrix.distro }}-r${{ matrix.release }}

      - name: Cleanup molecule
        if: always()
        run: molecule destroy -s ${{ matrix.scenario }}
        continue-on-error: true
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
