---
name: Test ElasticStack
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  schedule:
    - cron: "0 4 * * *"

jobs:
  lint_full:
    uses: ./.gitea/workflows/test_linting.yml
    with:
      rolename: ''

  molecule_full_stack_every_os:
    runs-on: ubuntu-latest
    needs: lint_full
    timeout-minutes: 60

    env:
      COLLECTION_NAMESPACE: oddly
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      matrix:
        distro:
          - rockylinux9
          - ubuntu2204
          - ubuntu2404
          - debian11
          - debian12
          - debian13
        scenario:
          - elasticstack_default
          - es_kibana
          - logstash_elasticsearch
          - cert_renewal
        release:
          - 8
          - 9
        # Rocky 10 excluded: EPEL 10 does not ship Redis yet.
        # Rocky 10 is still tested via the ES modules workflow.

    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1


      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: uv pip install --system --break-system-packages --python /usr/bin/python3 -r requirements-test.txt
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a ../ansible-collection-$COLLECTION_NAME ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with molecule
        run: molecule test -s ${{ matrix.scenario }} --destroy=never
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_DIFF_ALWAYS: 'true'
          ANSIBLE_CALLBACKS_ENABLED: profile_tasks
          ELASTIC_RELEASE: ${{ matrix.release }}

      - name: Collect and upload diagnostics
        if: failure()
        uses: ./.github/actions/collect-diagnostics
        with:
          artifact-name: diag-${{ matrix.scenario }}-${{ matrix.distro }}-r${{ matrix.release }}

      - name: Cleanup molecule
        if: always()
        run: molecule destroy -s ${{ matrix.scenario }}
        continue-on-error: true
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
