---
- name: Converge
  hosts: all
  collections:
    - oddly.elasticstack
  vars:
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | default('9', true) | int }}"
    elasticstack_full_stack: false
    elasticstack_no_log: false
    logstash_output_elasticsearch: false
    logstash_create_user: false
    logstash_create_role: false
    logstash_input_beats_ssl: false
    logstash_pipeline_unsafe_shutdown: true
    logstash_filters: |
      grok {
        match => { "message" => "%{SYSLOGLINE}" }
      }
      date {
        match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      }
    logstash_extra_outputs: |
      file {
        path => "/var/log/logstash/standalone-output.log"
      }
  tasks:
    - name: Include Elastic repos role
      ansible.builtin.include_role:
        name: repos

    - name: Include Logstash role
      ansible.builtin.include_role:
        name: logstash
