---
prerun: false
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: "ls-def-${MOLECULE_DISTRO:-debian12}-r${ELASTIC_RELEASE:-9}"
    groups:
      - logstash
    distro: "${MOLECULE_DISTRO:-debian12}"
    memory_mb: 1024
provisioner:
  name: ansible
  env:
    ANSIBLE_LOG_PATH: /var/log/ansible.log
  connection_options:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_retries: 3
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o "ProxyCommand=ssh -o StrictHostKeyChecking=no -o BatchMode=yes
      -i ${MOLECULE_SSH_KEY:-~/.ssh/molecule_id_ed25519}
      -W %h:%p root@${INCUS_HOST:-172.30.0.172}"
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
