---

- name: restart_and_verify_beat | Restart and verify beat  # noqa: name[template]
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/../elasticstack/tasks/restart_and_verify_service.yml"
  vars:
    _service_name: "{{ _beat_service_name }}"
