---
# Real-world scenario: Logstash with a fully custom pipeline definition.
# Uses logstash_custom_pipeline to give full control over the pipeline config
# instead of the built-in input/filter/output template system. This is how
# power users run Logstash when the template system is too limiting.
- name: Deploy Logstash with custom pipeline
  hosts: all
  vars:
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | default('9', true) | int }}"
    elasticstack_full_stack: false
    elasticstack_no_log: false
    logstash_output_elasticsearch: false
    logstash_create_user: false
    logstash_create_role: false
    logstash_pipeline_unsafe_shutdown: true
    # Full custom pipeline - this uses the logstash_custom_pipeline variable
    # which bypasses the normal input/filter/output template system
    logstash_custom_pipeline: |
      input {
        generator {
          lines => [
            '{"timestamp": "2026-01-15T10:00:00Z", "level": "INFO", "service": "api", "message": "Request processed"}',
            '{"timestamp": "2026-01-15T10:00:01Z", "level": "WARN", "service": "auth", "message": "Token expiring soon"}',
            '{"timestamp": "2026-01-15T10:00:02Z", "level": "ERROR", "service": "db", "message": "Connection timeout"}'
          ]
          count => 1
          codec => json
        }
      }

      filter {
        if [level] == "ERROR" {
          mutate {
            add_tag => ["alert"]
          }
        }

        mutate {
          add_field => {
            "[@metadata][pipeline]" => "custom"
            "processed_by" => "logstash-custom"
          }
        }
      }

      output {
        file {
          path => "/var/log/logstash/custom-output.log"
          codec => json_lines
        }
        stdout {
          codec => rubydebug
        }
      }
  tasks:
    - name: Include Elastic repos
      ansible.builtin.include_role:
        name: oddly.elasticstack.repos

    - name: Deploy Logstash
      ansible.builtin.include_role:
        name: oddly.elasticstack.logstash
