---

# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722

- name: Converge
  collections:
    - oddly.elasticstack
  hosts: all
  vars:
    elasticsearch_jna_workaround: true
    elasticsearch_monitoring_enabled: false
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | default('9', true) | int }}"
    elasticsearch_heap: "1"
    elasticstack_full_stack: true
    elasticstack_no_log: false
    logstash_pipeline_unsafe_shutdown: true
    beats_filebeat_journald: true
    beats_filebeat_modules:
      - system
    beats_auditbeat: true
    beats_auditbeat_enable: false  # can't run in Docker (permissions)
    beats_metricbeat: true
    beats_fields:
      - "testbed: molecule"
    kibana_extra_config: |-
      ops.interval: 5000
  tasks:
    - name: Enable Elastic installation on RHEL 9
      ansible.builtin.set_fact:
        elasticstack_rpm_workaround: true
      when: ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version >= "9"
    - name: Include Elastic Repos
      ansible.builtin.include_role:
        name: repos
    - name: Include Elasticsearch role
      ansible.builtin.include_role:
        name: elasticsearch
    - name: Include logstash
      ansible.builtin.include_role:
        name: logstash
    - name: Include kibana
      ansible.builtin.include_role:
        name: kibana
    - name: Include Beats
      ansible.builtin.include_role:
        name: beats
