---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "elasticstack${ELASTIC_RELEASE}-cluster1-${MOLECULE_DISTRO}"
    groups:
      - beats
      - logstash
      - elasticsearch
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: "elasticstack${ELASTIC_RELEASE}-cluster2-${MOLECULE_DISTRO}"
    groups:
      - beats
      - kibana
      - elasticsearch
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    group_vars:
      all:
        # Force Ansible to use /usr/bin/python3 which points to python3.12 on RHEL 8
        # after our prepare.yml bootstrap (RHEL 8 ships Python 3.6 which is unsupported)
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      elasticstack${ELASTIC_RELEASE}-cluster2-${MOLECULE_DISTRO}:
        elasticsearch_tls_key_passphrase: UniqueHostPassword
      # Use Python 3.12 on Rocky Linux 8 (system Python 3.6 is unsupported)
      elasticstack${ELASTIC_RELEASE}-cluster1-rockylinux8:
        ansible_python_interpreter: /usr/bin/python3.12
      elasticstack${ELASTIC_RELEASE}-cluster2-rockylinux8:
        ansible_python_interpreter: /usr/bin/python3.12

  # Just enable temporarily. Sometimes it's useful, but most of the time it's
  # overwhelming
  #env:
  #  ANSIBLE_VERBOSITY: 3
verifier:
  name: ansible
