---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "elasticstack${ELASTIC_RELEASE}-cluster1-${MOLECULE_DISTRO}"
    groups:
      - beats
      - logstash
      - elasticsearch
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: "elasticstack${ELASTIC_RELEASE}-cluster2-${MOLECULE_DISTRO}"
    groups:
      - beats
      - kibana
      - elasticsearch
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      elasticstack${ELASTIC_RELEASE}-cluster2-${MOLECULE_DISTRO}:
        elasticsearch_tls_key_passphrase: UniqueHostPassword

  # Just enable temporarily. Sometimes it's useful, but most of the time it's
  # overwhelming
  #env:
  #  ANSIBLE_VERBOSITY: 3
verifier:
  name: ansible
