---
prerun: false
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: "elasticstack${ELASTIC_RELEASE:-9}-cluster1-${MOLECULE_DISTRO:-debian12}${MOLECULE_RUN_SUFFIX}"
    groups:
      - beats
      - logstash
      - elasticsearch
    distro: "${MOLECULE_DISTRO:-debian12}"
    memory_mb: 7680
  - name: "elasticstack${ELASTIC_RELEASE:-9}-cluster2-${MOLECULE_DISTRO:-debian12}${MOLECULE_RUN_SUFFIX}"
    groups:
      - beats
      - kibana
      - elasticsearch
    distro: "${MOLECULE_DISTRO:-debian12}"
    memory_mb: 7680
provisioner:
  name: ansible
  env:
    ANSIBLE_LOG_PATH: /var/log/ansible.log
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  connection_options:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      elasticstack${ELASTIC_RELEASE:-9}-cluster2-${MOLECULE_DISTRO:-debian12}${MOLECULE_RUN_SUFFIX}:
        elasticsearch_tls_key_passphrase: UniqueHostPassword

  # Just enable temporarily. Sometimes it's useful, but most of the time it's
  # overwhelming
  # env:
  #   ANSIBLE_VERBOSITY: 3
verifier:
  name: ansible
