---
- name: Prepare
  hosts: all
  tasks:
    - name: Populate /etc/hosts with molecule instances
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}$"
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
      loop: "{{ groups['all'] }}"
      when: groups['all'] | length > 1

    - name: Clean dnf cache for RHEL
      ansible.builtin.command: dnf clean all
      changed_when: false
      when: ansible_facts.os_family == "RedHat"

    - name: Install packages for RHEL
      ansible.builtin.package:
        name:
          - iproute
          - NetworkManager
      when: ansible_facts.os_family == "RedHat"
      retries: 3
      delay: 10
      register: rhel_packages
      until: rhel_packages is success

    - name: Start NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: started
        enabled: true
      when: ansible_facts.os_family == "RedHat"

    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
        update_cache: true
      when: ansible_facts.os_family == "Debian"

    - name: Install common packages
      ansible.builtin.package:
        name:
          - git
          - openssl
          - unzip
          - systemd
      retries: 3
      delay: 10
      register: common_packages
      until: common_packages is success
