---
# First play: Bootstrap Python 3.9 on RHEL 8 before any Python-dependent tasks
# This is needed because community.general 12.x requires Python 3.7+ but RHEL 8 ships with 3.6
- name: Bootstrap Python 3.9 on RHEL 8
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if this is RHEL 8 (using raw module to avoid Python dependency)
      ansible.builtin.raw: |
        if [ -f /etc/redhat-release ] && grep -q "release 8" /etc/redhat-release; then
          echo "rhel8"
        else
          echo "other"
        fi
      register: os_check
      changed_when: false

    - name: Install Python 3.9 on RHEL 8
      ansible.builtin.raw: dnf install -y python39 python39-pip
      when: "'rhel8' in os_check.stdout"
      changed_when: true

# Second play: Normal preparation with facts gathering
- name: Prepare
  hosts: all
  tasks:
    - name: Install Python 3.9 on RHEL 8 (required for community.general 12.x)
      ansible.builtin.dnf:
        name:
          - python39
          - python39-pip
        state: present
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "8"

    - name: Install packages for RHEL
      ansible.builtin.package:
        name:
          - iproute
          - NetworkManager
      when: ansible_os_family == "RedHat"

    - name: Start NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install common packages
      ansible.builtin.package:
        name:
          - git
          - openssl
          - unzip
          - systemd

# KICS complains about packages being updated.
# In this case, a mere test scenario it is OK, though.

    - name: Update all installed packages RHEL
      ansible.builtin.yum:
        name: '*'
# kics-scan ignore-line
        state: latest
        update_cache: yes
        update_only: yes
      when: ansible_os_family == "RedHat"

    - name: Update all installed packages Debian
      ansible.builtin.apt:
        name: '*'
# kics-scan ignore-line
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"
