---
- name: Prepare
  hosts: all
  vars:
    distro_cache_url: "{{ lookup('env', 'DISTRO_CACHE_URL') }}"
  tasks:
    - name: Common prepare tasks
      ansible.builtin.include_tasks: ../shared/prepare_common.yml

    - name: Install apt-transport-https for Debian
      ansible.builtin.apt:
        name:
          - apt-transport-https
        update_cache: false
      when: ansible_facts.os_family == "Debian"
