---
- name: Prepare
  hosts: all
  tasks:
    - name: Install requirements for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - apt-transport-https
        update_cache: true
      when: ansible_facts.os_family == "Debian"
    - name: Install requirements for Ubuntu
      ansible.builtin.apt:
        name:
          - gpg-agent
        update_cache: true
      when: ansible_facts.os_family == "Debian" and ansible_facts.distribution == "Ubuntu"
