---
- name: Import shared Molecule preparation
  import_playbook: ../shared/prepare.yml

- name: Prepare repository scenario extras
  hosts: all
  tasks:
    - name: Install apt-transport-https for Debian
      ansible.builtin.apt:
        name:
          - apt-transport-https
        update_cache: false
      when: ansible_facts.os_family == "Debian"
