---
prerun: false
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: "es-extcrt-${MOLECULE_DISTRO:-debian12}-r${ELASTIC_RELEASE:-9}${MOLECULE_RUN_SUFFIX}"
    groups:
      - elasticsearch
    distro: "${MOLECULE_DISTRO:-debian12}"
    memory_mb: 3328
provisioner:
  name: ansible
  env:
    ANSIBLE_LOG_PATH: /var/log/ansible.log
  connection_options:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
