---
# handlers file for kibana
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Kibana
  ansible.builtin.include_tasks: restart_and_verify_kibana.yml
  when:
    - not ansible_check_mode
    - kibana_enable | bool
    - not kibana_freshstart.changed | bool
