---
# Molecule scenario for testing single-node Elasticsearch 8.x to 9.x upgrade
# Simpler test case than multi-node cluster upgrade
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "es_upgrade_single-${MOLECULE_DISTRO:-debian11}"
    groups:
      - elasticsearch
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      # Use Python 3.12 on Rocky Linux 8 (system Python 3.6 is unsupported)
      es_upgrade_single-rockylinux8:
        ansible_python_interpreter: /usr/bin/python3.12
verifier:
  name: ansible
