---
- name: Verify Logstash SSL deployment
  hosts: all
  tasks:
    - name: Check Logstash service is running
      ansible.builtin.service:
        name: logstash
        state: started
      check_mode: true
      register: logstash_service
      failed_when: logstash_service.changed

    # --- Certificate verification ---

    - name: Check certificate directory exists
      ansible.builtin.stat:
        path: /etc/logstash/certs
      register: certs_dir
      failed_when: not certs_dir.stat.exists

    - name: Check server certificate exists
      ansible.builtin.stat:
        path: "/etc/logstash/certs/{{ inventory_hostname }}-server.crt"
      register: server_cert
      failed_when: not server_cert.stat.exists

    - name: Check PKCS8 key exists
      ansible.builtin.stat:
        path: "/etc/logstash/certs/{{ inventory_hostname }}-pkcs8.key"
      register: pkcs8_key
      failed_when: not pkcs8_key.stat.exists

    - name: Check CA certificate exists
      ansible.builtin.stat:
        path: /etc/logstash/certs/ca.crt
      register: ca_cert
      failed_when: not ca_cert.stat.exists

    - name: Verify certificate permissions
      ansible.builtin.assert:
        that:
          - server_cert.stat.mode == '0640'
          - pkcs8_key.stat.mode == '0640'
          - ca_cert.stat.mode == '0640'
        fail_msg: "Certificate file permissions are not correct (expected 0640)"

    # --- Input verification (elastic_agent with SSL) ---

    - name: Read input configuration
      ansible.builtin.slurp:
        src: /etc/logstash/conf.d/main/10-input.conf
      register: input_content

    - name: Verify elastic_agent input is configured with SSL
      ansible.builtin.assert:
        that:
          - "'elastic_agent {' in (input_content.content | b64decode)"
          - "'port => 5044' in (input_content.content | b64decode)"
          - "'ssl_enabled => true' in (input_content.content | b64decode) or 'ssl => true' in (input_content.content | b64decode)"
          - "'ssl_certificate' in (input_content.content | b64decode)"
          - "'ssl_key' in (input_content.content | b64decode)"
        fail_msg: "Elastic Agent input with SSL not properly configured"

    - name: Verify beats input is NOT configured
      ansible.builtin.assert:
        that:
          - "'beats {' not in (input_content.content | b64decode)"
        fail_msg: "Beats input should not be present when disabled"

    # --- Service health ---

    - name: Show Logstash log before port check
      ansible.builtin.shell: >-
        journalctl -u logstash --no-pager -n 50 2>/dev/null ||
        tail -50 /var/log/logstash/logstash-plain.log 2>/dev/null ||
        echo "No logs found"
      register: logstash_log_before
      changed_when: false

    - name: Display Logstash log  # noqa: no-handler
      ansible.builtin.debug:
        var: logstash_log_before.stdout_lines

    - name: Check Logstash is listening on port 5044
      ansible.builtin.wait_for:
        port: 5044
        timeout: 300
        state: started
      register: port_check
      ignore_errors: true

    - name: Show diagnostics on port check failure
      when: port_check is failed
      block:
        - name: Show Logstash log after failure
          ansible.builtin.shell: >-
            journalctl -u logstash --no-pager -n 100 2>/dev/null ||
            tail -100 /var/log/logstash/logstash-plain.log 2>/dev/null ||
            echo "No logs found"
          register: logstash_log_after
          changed_when: false

        - name: Display failure log  # noqa: no-handler
          ansible.builtin.debug:
            var: logstash_log_after.stdout_lines

        - name: Show listening ports
          ansible.builtin.shell: ss -tlnp | grep -E '5044|logstash|java' || echo "No matching ports"
          register: listening_ports
          changed_when: false

        - name: Display listening ports  # noqa: no-handler
          ansible.builtin.debug:
            var: listening_ports.stdout_lines

        - name: Fail with context
          ansible.builtin.fail:
            msg: "Logstash port 5044 did not open within timeout. Check logs above."

    # --- Config syntax validation ---

    - name: Get installed Logstash version
      ansible.builtin.shell: >-
        (v=$(dpkg-query -W -f='${Version}' logstash 2>/dev/null) &&
        echo "${v}" | sed 's/^[0-9]*://;s/-.*$//') ||
        rpm -q --qf '%{VERSION}' logstash 2>/dev/null
      register: logstash_version
      changed_when: false

    - name: Verify Logstash config syntax
      ansible.builtin.command: >-
        /usr/share/logstash/bin/logstash
        --path.settings=/etc/logstash
        --config.test_and_exit
        -f /etc/logstash/conf.d/main/
      become: "{{ logstash_version.stdout is version('9.0.0', '>=', version_type='loose') }}"
      become_user: "{{ 'logstash' if logstash_version.stdout is version('9.0.0', '>=', version_type='loose') else omit }}"
      register: config_test
      changed_when: false
      failed_when: config_test.rc != 0
