---
- name: Verify Logstash filter configuration
  hosts: all
  tasks:
    - name: Check Logstash service is running
      ansible.builtin.service:
        name: logstash
        state: started
      check_mode: true
      register: logstash_service
      failed_when: logstash_service.changed

    - name: Check filter configuration exists
      ansible.builtin.stat:
        path: /etc/logstash/conf.d/main/50-filter.conf
      register: filter_conf
      failed_when: not filter_conf.stat.exists

    - name: Read filter configuration
      ansible.builtin.slurp:
        src: /etc/logstash/conf.d/main/50-filter.conf
      register: filter_content

    - name: Verify grok filter is configured
      ansible.builtin.assert:
        that:
          - "'grok {' in (filter_content.content | b64decode)"
          - "'SYSLOGLINE' in (filter_content.content | b64decode)"
        fail_msg: "Grok filter not properly configured"

    - name: Verify date filter is configured
      ansible.builtin.assert:
        that:
          - "'date {' in (filter_content.content | b64decode)"
        fail_msg: "Date filter not properly configured"

    - name: Check output configuration exists
      ansible.builtin.stat:
        path: /etc/logstash/conf.d/main/90-output.conf
      register: output_conf
      failed_when: not output_conf.stat.exists

    - name: Read output configuration
      ansible.builtin.slurp:
        src: /etc/logstash/conf.d/main/90-output.conf
      register: output_content

    - name: Verify stdout output is configured (extra_outputs)
      ansible.builtin.assert:
        that:
          - "'stdout {' in (output_content.content | b64decode)"
          - "'rubydebug' in (output_content.content | b64decode)"
        fail_msg: "Extra stdout output not properly configured"

    - name: Verify Logstash config syntax
      ansible.builtin.command: /usr/share/logstash/bin/logstash --config.test_and_exit -f /etc/logstash/conf.d/main/
      register: config_test
      changed_when: false
      failed_when: config_test.rc != 0
