---
- name: Fail when security is disabled
  ansible.builtin.fail:
    msg: "Elasticsearch requires enabled security. Set elasticsearch_security to true"
  when:
    - elasticsearch_security is not defined or not elasticsearch_security
