---

- name: restart_and_verify_elasticsearch | Restart and verify Elasticsearch
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/../elasticstack/tasks/restart_and_verify_service.yml"
  vars:
    _service_name: elasticsearch
    _daemon_reload: true
