---
# Molecule scenario to verify OSS variant is rejected for ES 9.x
# This test SHOULD FAIL during converge - that's the expected behavior
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "es_oss_9x_fail-${MOLECULE_DISTRO:-debian11}"
    groups:
      - elasticsearch
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
