---
- name: Verify Elastic Agent input configuration
  hosts: all
  tasks:
    - name: Check Logstash service is running
      ansible.builtin.service:
        name: logstash
        state: started
      check_mode: true
      register: logstash_service
      failed_when: logstash_service.changed

    - name: Check input configuration exists
      ansible.builtin.stat:
        path: /etc/logstash/conf.d/main/10-input.conf
      register: input_conf
      failed_when: not input_conf.stat.exists

    - name: Read input configuration
      ansible.builtin.slurp:
        src: /etc/logstash/conf.d/main/10-input.conf
      register: input_content

    - name: Verify elastic_agent input is configured
      ansible.builtin.assert:
        that:
          - "'elastic_agent {' in (input_content.content | b64decode)"
          - "'port => 5044' in (input_content.content | b64decode)"
        fail_msg: "Elastic Agent input not properly configured"

    - name: Verify beats input is NOT configured
      ansible.builtin.assert:
        that:
          - "'beats {' not in (input_content.content | b64decode)"
        fail_msg: "Beats input should not be present when disabled"

    - name: Verify SSL is enabled for elastic_agent
      ansible.builtin.assert:
        that:
          - "'ssl_enabled => true' in (input_content.content | b64decode)"
          - "'ssl_certificate' in (input_content.content | b64decode)"
          - "'ssl_key' in (input_content.content | b64decode)"
          - "'ssl_client_authentication => required' in (input_content.content | b64decode)"
        fail_msg: "SSL not properly configured for Elastic Agent input"

    - name: Check Logstash is listening on port 5044
      ansible.builtin.wait_for:
        port: 5044
        timeout: 60
        state: started

    - name: Verify Logstash config syntax
      ansible.builtin.command: /usr/share/logstash/bin/logstash --config.test_and_exit -f /etc/logstash/conf.d/main/
      register: config_test
      changed_when: false
      failed_when: config_test.rc != 0
