---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kibana_default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
