---
- name: Prepare
  hosts: all
  vars:
    es_release: "{{ lookup('env', 'ELASTIC_RELEASE') | default('9', true) | int }}"
  tasks:
    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
          - git
          - openssl
          - python3
          - python3-pip
          - python3-setuptools
        update_cache: true
      when: ansible_facts.os_family == "Debian"

    - name: Install packages for RedHat
      ansible.builtin.yum:
        name:
          - python3-pip
          - python3-setuptools
      when: ansible_facts.os_family == "RedHat"

    - name: Remove PEP 668 marker (test containers only)
      ansible.builtin.file:
        path: "/usr/lib/python{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED"
        state: absent

    - name: Install python module dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - "elasticsearch>={{ es_release }},<{{ es_release | int + 1 }}"
