---
# First play: Bootstrap Python 3.9 on RHEL 8 before any Python-dependent tasks
# This is needed because community.general 12.x requires Python 3.7+ but RHEL 8 ships with 3.6
- name: Bootstrap Python 3.9 on RHEL 8
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if this is RHEL 8 (using raw module to avoid Python dependency)
      ansible.builtin.raw: |
        if [ -f /etc/redhat-release ] && grep -q "release 8" /etc/redhat-release; then
          echo "rhel8"
        else
          echo "other"
        fi
      register: os_check
      changed_when: false

    - name: Install Python 3.9 on RHEL 8
      ansible.builtin.raw: dnf install -y python39 python39-pip
      when: "'rhel8' in os_check.stdout"
      changed_when: true

    - name: Set Python 3.9 as default python3 on RHEL 8
      ansible.builtin.raw: |
        alternatives --set python3 /usr/bin/python3.9 2>/dev/null || \
        ln -sf /usr/bin/python3.9 /usr/bin/python3
      when: "'rhel8' in os_check.stdout"
      changed_when: true

# Second play: Normal preparation with facts gathering
- name: Prepare
  hosts: all
  vars:
    es_release: "{{ lookup('env', 'ELASTIC_RELEASE') | default('8') | int }}"
  tasks:
    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
          - git
          - openssl
          - python3
          - python3-pip
          - python3-setuptools
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install packages for RedHat
      ansible.builtin.yum:
        name:
          - python3-pip
          - python3-setuptools
      when: ansible_os_family == "RedHat"

    - name: Remove PEP 668 marker (test containers only)
      ansible.builtin.file:
        path: "/usr/lib/python{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED"
        state: absent

    - name: Install python module dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: "{{ 'pip3.9' if (ansible_distribution_major_version | default('0')) == '8' and ansible_os_family == 'RedHat' else omit }}"
      loop:
        - "elasticsearch>={{ es_release }},<{{ es_release | int + 1 }}"
