---
name: Test Elasticsearch modules
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    paths:
      - 'roles/elasticsearch/**'
      - 'roles/elasticstack/**'
      - 'molecule/elasticsearch_test_modules/**'
      - 'molecule/shared/**'
      - '.github/workflows/test_elasticsearch_modules.yml'
      - '.github/workflows/molecule.yml'
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_elasticsearch:
    uses: ./.github/workflows/test_linting.yml
    with:
      rolename: elasticsearch
    secrets: inherit

  molecule_elasticsearch_modules:
    needs: lint_elasticsearch
    uses: ./.github/workflows/molecule.yml
    with:
      scenarios: '["elasticsearch_test_modules"]'
      distros: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '["rockylinux10","debian13"]' || '["rockylinux9","rockylinux10","ubuntu2204","ubuntu2404","debian12","debian13"]' }}
      timeout: 20
    secrets: inherit
