---
name: Test Role Kibana
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    paths:
      - 'roles/kibana/**'
      - 'roles/elasticstack/**'
      - 'molecule/kibana_**'
      - 'molecule/shared/**'
      - '.github/workflows/test_role_kibana.yml'
      - '.github/workflows/molecule.yml'
  schedule:
    - cron: "30 3 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_kibana:
    uses: ./.github/workflows/test_linting.yml
    with:
      rolename: kibana
    secrets: inherit

  molecule_kibana:
    needs: lint_kibana
    uses: ./.github/workflows/molecule.yml
    with:
      scenarios: '["kibana_default","kibana_custom","kibana_custom_certs"]'
      distros: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '["rockylinux10","debian13"]' || '["rockylinux9","rockylinux10","ubuntu2204","ubuntu2404","debian12","debian13"]' }}
    secrets: inherit
